xarm:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      xarm_6_joint:
        type: position_controllers/JointPositionController
        joint: xarm_6_joint
        pid: {p: 10.0, i: 0.0, d: 1.0}
      
        